name: Multi container application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run react tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build client docker image
        run: docker build -t subash/multi-docker-client -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true subash/multi-docker-client npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build server docker image
        run: docker build -t subash/multi-docker-server ./server

      - name: Build worker docker image
        run: docker build -t subash/multi-docker-worker ./worker

      - name: Build client docker image
        run: docker build -t subash/multi-docker-client ./client

      - name: Build nginx docker image
        run: docker build -t subash/multi-docker-nginx ./nginx

        # Log in to docker cli
      - name: Login to docker hub
        run: echo ${{ vars.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_ID }} --password-stdin

        # Take those images and push them docker hub
      - name: Push images to docker hub
        run: |
          docker push subash/multi-docker-server
          docker push subash/multi-docker-worker
          docker push subash/multi-docker-client
          docker push subash/multi-docker-nginx